### PR TITLE
*: build gromacs verbose

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
In the other build:
```
2021-06-11T23:00:14.1995665Z [ 29%] Building CXX object src/gromacs/CMakeFiles/libgromacs_external.dir/linearalgebra/gmx_lapack/slasq3.cpp.o
2021-06-11T23:00:14.2010281Z cd /__w/votca/votca/builddir/gromacs/src/Gromacs_build-build/src/gromacs && /usr/lib64/ccache/g++ -DGMX_DOUBLE=0 -DHAVE_CONFIG_H -I/__w/votca/votca/builddir/gromacs/src/Gromacs_build-build/src -I/__w/votca/votca/builddir/gromacs/src/Gromacs_build/src -isystem /__w/votca/votca/builddir/gromacs/src/Gromacs_build/src/external/thread_mpi/include -mavx512f -mfma    -std=c++11   -O3 -DNDEBUG -funroll-all-loops -fexcess-precision=fast   -fPIC -MD -MT src/gromacs/CMakeFiles/libgromacs_external.dir/linearalgebra/gmx_lapack/slasq3.cpp.o -MF CMakeFiles/libgromacs_external.dir/linearalgebra/gmx_lapack/slasq3.cpp.o.d -o CMakeFiles/libgromacs_external.dir/linearalgebra/gmx_lapack/slasq3.cpp.o -c /__w/votca/votca/builddir/gromacs/src/Gromacs_build/src/gromacs/linearalgebra/gmx_lapack/slasq3.cpp
2021-06-11T23:00:15.4761108Z during RTL pass: expand
2021-06-11T23:00:15.4762944Z /__w/votca/votca/builddir/gromacs/src/Gromacs_build/src/gromacs/linearalgebra/gmx_lapack/slasq3.cpp: In function 'void slasq3_(int*, int*, float*, int*, float*, float*, float*, float*, int*, int*, int*, int*)':
2021-06-11T23:00:15.4767684Z /__w/votca/votca/builddir/gromacs/src/Gromacs_build/src/gromacs/linearalgebra/gmx_lapack/slasq3.cpp:112:48: internal compiler error: in ix86_expand_vector_init_concat, at config/i386/i386-expand.c:14081
2021-06-11T23:00:15.4770785Z   112 |                 z__[j4 - 3] = z__[ipn4 - j4 - 3];
2021-06-11T23:00:15.4771278Z       |                               ~~~~~~~~~~~~~~~~~^
2021-06-11T23:00:15.4771794Z Please submit a full bug report,
2021-06-11T23:00:15.4772450Z with preprocessed source if appropriate.
2021-06-11T23:00:15.4773425Z See <http://bugzilla.redhat.com/bugzilla> for instructions.
2021-06-11T23:00:15.4774569Z Preprocessed source stored into /tmp/ccp3Nm5V.out file, please attach this to your bugreport.
2021-06-11T23:00:15.4776908Z gmake[5]: *** [src/gromacs/CMakeFiles/libgromacs_external.dir/build.make:2694: src/gromacs/CMakeFiles/libgromacs_external.dir/linearalgebra/gmx_lapack/slasq3.cpp.o] Error 1
2021-06-11T23:00:15.4778429Z gmake[4]: *** [CMakeFiles/Makefile2:3457: src/gromacs/CMakeFiles/libgromacs_external.dir/all] Error 2
2021-06-11T23:00:15.4779350Z gmake[4]: *** Waiting for unfinished jobs....
2021-06-11T23:00:15.4780535Z gmake[5]: Leaving directory '/__w/votca/votca/builddir/gromacs/src/Gromacs_build-build'
2021-06-11T23:00:15.4862034Z [ 29%] Building CXX object 
```

So let's see if it is compiled here with the same options.

**Comment by junghans** [comment]
@JensWehner very strange here:
```
2021-06-12T13:51:40.3504182Z [ 25%] Building CXX object src/gromacs/CMakeFiles/libgromacs_external.dir/linearalgebra/gmx_lapack/slasq3.cpp.o
2021-06-12T13:51:40.3522301Z cd /home/votca/gromacs/build/src/gromacs && /usr/lib64/ccache/c++ -DGMX_DOUBLE=0 -DHAVE_CONFIG_H -I/home/votca/gromacs/build/src -I/home/votca/gromacs/src -isystem /home/votca/gromacs/src/external/thread_mpi/include -msse2    -std=c++11  -Wstringop-truncation -Wundef -Wextra -Wno-missing-field-initializers -Wpointer-arith -Wmissing-declarations -Wall  -O3 -DNDEBUG -funroll-all-loops -fexcess-precision=fast  -Wno-array-bounds  -fPIC -Wno-stringop-truncation -MD -MT src/gromacs/CMakeFiles/libgromacs_external.dir/linearalgebra/gmx_lapack/slasq3.cpp.o -MF CMakeFiles/libgromacs_external.dir/linearalgebra/gmx_lapack/slasq3.cpp.o.d -o CMakeFiles/libgromacs_external.dir/linearalgebra/gmx_lapack/slasq3.cpp.o -c /home/votca/gromacs/src/gromacs/linearalgebra/gmx_lapack/slasq3.cpp
``` 

works!

**Comment by junghans** [comment]
Ok the difference is `-mavx512f -mfma` vs `-msse2`.

**Comment by JensWehner** [comment]
how did the verbose part fix this?

**Comment by JensWehner** [comment]
Is this in principle not a bug we should file against gromacs?

**Comment by junghans** [comment]
> how did the verbose part fix this?

The verbose part didn’t fix anything it just helped me to see where the gromacs build on container and in `BUILD_OWN_GROMACS` differs.

**Comment by junghans** [comment]
> Is this in principle not a bug we should file against gromacs?

It is not a gromacs bug, but a GCC one, so reported it there:

https://bugzilla.redhat.com/show_bug.cgi?id=1971171

**Pull request merged**
