### PR TITLE
*: add gmx2020 builds

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
Need to wait for @acmnpv to create the `release-2020` branch.

**Comment by acmnpv** [comment]
release-2020 branch of GROMACS has been created now

**Comment by junghans** [comment]
@acmnpv when does the branch get pushed out to the GitHub mirror?

**Comment by acmnpv** [comment]
@junghans I need to check with the others here why the branch did not get pushed automatically. Will get back to you

**Comment by acmnpv** [comment]
@junghans the branch exists now

**Pull request merged**
